[WIP] Testing redis CI with dummy test
TykTechnologies/storage pull request #83
Opened 2023-11-02 14:08 UTC by mativm02

## Description

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] I have [reviewed the guidelines](./CONTRIBUTING.md) for contributing to this repository.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
     - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
    - [ ] `gofmt -s -w .`
    - [ ] `go vet ./...`

2023-11-03 14:21 UTC, sredxny approved these changes

2023-11-03 15:48 UTC, tbuchaillot requested changes
As we talked, let's try a more generic taskfile approach!

2023-11-03 15:48 UTC, tbuchaillot commented on bin/temporal-storage-tests.sh
> +#!/bin/bash
this is pretty much duplicated of `ci-test.sh`, let's make it more generic.

2023-11-06 16:22 UTC, tbuchaillot approved these changes
Looks good overall @mativm02  - left some small comments

2023-11-06 16:22 UTC, tbuchaillot commented on .github/workflows/ci-tests.yml
> +      - name: Install Task runner
you can use task github action like here https://github.com/TykTechnologies/opentelemetry/blob/main/.github/workflows/ci-tests.yml#L18

2023-11-06 16:22 UTC, tbuchaillot commented on .github/workflows/ci-tests.yml
> +      - name: Install Task runner
is this needed?

2023-11-06 16:22 UTC, tbuchaillot commented on .github/workflows/ci-tests.yml
> +      - if: ${{ matrix.database == 'redis' }}
What do you think about moving the Redis / mongo initialization to a helper taskfile? 
In that way, development testing can be the same as CI testing.

2023-11-07 16:35 UTC, merged