[TT-10388] Redis KeyValue implementation
TykTechnologies/storage pull request #84
Opened 2023-11-07 17:40 UTC by mativm02

## Description

Creating the KeyValue interface, along with its Redis implementation
## Related Issue

https://tyktech.atlassian.net/browse/TT-9476
## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] I have [reviewed the guidelines](./CONTRIBUTING.md) for contributing to this repository.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
     - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
    - [ ] `gofmt -s -w .`
    - [ ] `go vet ./...`

2023-11-08 20:58 UTC, sredxny requested changes

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/driver/redis8/redis8.go
> +type Redis8 struct {
I would call this pkg and the object `redisV8` wdyt?

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/driver/redis8/key_value.go
> +			return "", nil // or fmt.Errorf("key not found")?
I would return anyway `Key not found` so the caller function decide wether or not to print a log of key not found

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/driver/redis8/key_value.go
> +		return errors.New("key cannot be empty")
I guess we can normalize these errors? so they can be used across different drivers while maintaining consistency between them

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/driver/redis8/key_value.go
> +		return errors.New("key cannot be empty")
and yes, keys cannot be empty so can remove the comment

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/driver/redis8/key_value_test.go
> +func compareUnorderedSlices(t *testing.T, a, b []string) bool {
Can we move this to another pkg so a different implementation of the redis interface can access this as well?

2023-11-08 20:58 UTC, sredxny commented on temporal/internal/types/client_options.go
> +}
is this the same for any redis version? or can we have new fields in newer versions?

2023-11-08 20:58 UTC, sredxny commented on temporal/temporal.go
> +	Redis8 string = "redis-8"
what about `redisv8`, `redisv7` etc

2023-11-13 12:16 UTC, mativm02 commented on temporal/temporal.go
> +	Redis8 string = "redis-8"
added redisv9

2023-11-13 12:18 UTC, mativm02 commented on temporal/internal/types/client_options.go
> +}
It'd be impossible to know if there would be new fields in newer versions. At the moment, we're standardizing them and then, we parse them for each implementation. 
For example: if MaxActive changes its name in a future RedisV10 we can still use the same field name and in the RedisV10 implementation, we just adapt it to follow the new name.

2023-11-14 14:44 UTC, mativm02 commented on temporal/keyvalue/internal/driver/redisv8/redisv8.go
> +type RedisV8 struct {
should we change the name to something like `KeyValueRedisV8`?

having multiple RedisV8 for each interface (set, sorted set, etc.) can cause some confusion

2023-11-15 06:05 UTC, tbuchaillot commented on temporal/keyvalue/internal/driver/redisv8/redisv8.go
> +type RedisV8 struct {
agree

2023-11-15 11:37 UTC, tbuchaillot commented on temporal/keyvalue/internal/driver/redisv8/key_value.go
> +func (r *RedisV8) GetMulti(ctx context.Context, keys []string) ([]interface{}, error) {
Wdyt of renaming this to Multi get? also why []interface as response instead of []string?

2023-11-15 12:03 UTC, mativm02 commented on temporal/keyvalue/internal/driver/redisv8/key_value.go
> +func (r *RedisV8) GetMulti(ctx context.Context, keys []string) ([]interface{}, error) {
@tbuchaillot because the value of a key can be of a type different than a string - that's why cmd.Val() returns a slice of interfaces instead of a slice of strings

2023-11-15 14:26 UTC, sredxny approved these changes

2023-11-15 14:57 UTC, merged