[TT-10392] Adding Queue interface
TykTechnologies/storage pull request #91
Opened 2023-11-23 14:50 UTC by mativm02

## Description

A new Queue interface is created to handle PubSub connections.
## Related Issue

https://tyktech.atlassian.net/browse/TT-10392?atlOrigin=eyJpIjoiN2M3MGZiZjc3Y2VmNDg5NGE3MDdiOWQxOTYzYmI1YzQiLCJwIjoiaiJ9
## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] I have [reviewed the guidelines](./CONTRIBUTING.md) for contributing to this repository.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
     - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
    - [ ] `gofmt -s -w .`
    - [ ] `go vet ./...`

2023-11-23 15:26 UTC, tbuchaillot requested changes

2023-11-23 15:26 UTC, tbuchaillot commented on temporal/queue/queue_test.go
> +						redisMsg, ok := msg.(*redis.Message)
we need to abstract the subscription messages as well. We cannot depend on redis.Message

2023-11-23 15:26 UTC, tbuchaillot commented on temporal/internal/driver/redisv8/queue.go
> +	sub := r.client.Subscribe(ctx, channels...)
We need to handle and transform from this underlying response type to a common type that can be used across drivers.

2023-11-24 14:04 UTC, tbuchaillot requested changes

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/internal/driver/redisv8/queue.go
> +func (r *RedisV8) Subscribe(ctx context.Context, channels ...string) (model.Subscription, error) {
When this fn will error?

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/internal/driver/redisv8/queue.go
> +	return r.client.Publish(ctx, channel, message).Result()
Do we know when Publish error? can we normalize that?

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/queue/queue_test.go
> +		wantErr    bool
Can we change the `wantErr bool` for `expectedErr error`? Ideally, we need to raise the same errors independent of the driver.

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/queue/queue_test.go
> +		wantErr     bool
Same comment as above

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/internal/testutil/testutil.go
> +type MockConnector struct{}
Change name to `stub`

2023-11-24 14:04 UTC, tbuchaillot commented on temporal/internal/driver/redisv8/queue.go
> +	msg, err := r.pubSub.Receive(ctx)
When Receive will fail?

2023-11-24 14:17 UTC, mativm02 commented on temporal/internal/driver/redisv8/queue.go
> +func (r *RedisV8) Subscribe(ctx context.Context, channels ...string) (model.Subscription, error) {
It doesn't fail anymore since we're not executing the `sub.Receive()` method within this function anymore. Thanks!

2023-11-27 13:48 UTC, mativm02 commented on temporal/internal/driver/redisv8/queue.go
> +	return r.client.Publish(ctx, channel, message).Result()
I'll create a new PR normalizing errors from all methods

2023-11-27 14:12 UTC, sredxny approved these changes
Looks good! I would rename Queue to MessageBroker or similar that describes more the funtionality, but this is a topic for discussion

2023-11-28 17:57 UTC, tbuchaillot approved these changes

2023-11-29 12:03 UTC, merged